### ISSUE TITLE
Add RELEASE.md

### ISSUE THREAD

**Issue by julienbourdeau** [algolia/algoliasearch-client-common#5]
Create a new `RELEASE.md` file in each repository with the documentation of how to release the client.

**Comment by Haroenv** [comment]
Won't this sometimes need confidential information (like shared password for an account, unfortunately necessary in some cases), and thus make it useless to have this here, since another private document still needs to be found? I can also think of the purge URL for jsDelivr, which should stay private

**Comment by julienbourdeau** [comment]
In some cases yes. Ideally i'd like to store credentials elsewhere than in the current private doc. Although, I was not aware of this purge URL 🤔

**Comment by Haroenv** [comment]
maybe a RELEASE.md will force us to find a way to have better secrets though, that would be a nice improvement :)
